CREATE TABLE IF NOT EXISTS public.auth_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash text NOT NULL UNIQUE,
  service text NOT NULL,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  auth_type text NOT NULL,
  remember boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamptz NOT NULL,
  used_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_auth_tickets_service_active
ON public.auth_tickets (service, expires_at)
WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_auth_tickets_user_recent
ON public.auth_tickets (user_id, created_at DESC);
