import pool from '../db.js';

export async function ensureAuthTables() {
    await pool.query(`
        CREATE TABLE IF NOT EXISTS public.auth_tickets (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            token_hash TEXT NOT NULL UNIQUE,
            service TEXT NOT NULL,
            user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            auth_type TEXT NOT NULL,
            remember BOOLEAN NOT NULL DEFAULT false,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMPTZ NOT NULL,
            used_at TIMESTAMPTZ
        )
    `);

    await pool.query(`
        CREATE INDEX IF NOT EXISTS idx_auth_tickets_service_active
        ON public.auth_tickets (service, expires_at)
        WHERE used_at IS NULL
    `);

    await pool.query(`
        CREATE INDEX IF NOT EXISTS idx_auth_tickets_user_recent
        ON public.auth_tickets (user_id, created_at DESC)
    `);
}
